### ISSUE TITLE
Can you generate dependency to gradle implementation ?

### ISSUE THREAD

**Issue by marekbil** [iRYO400/sliding-panel#4]

**Comment by iRYO400** [comment]
Hi! It's not available because of `jCenter()`, it has been deprecated.
But you can use `jitpack`:

`implementation 'com.github.iRYO400:sliding-panel:1.0.0'`

**Comment by iRYO400** [comment]
Later will upload it to Maven

**Comment by marekbil** [comment]
Ok I implementation 'com.github.iRYO400:sliding-panel:1.0.0'
but not found
com.akbolatss.workshop.slidingpanel.SlidingPanelLayout
in my layout
<com.akbolatss.workshop.slidingpanel.SlidingPanelLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:id="@+id/sliding_panel"
  android:layout_width="match_parent"
  android:layout_height="match_parent"

  app:orientation="vertical"
  app:nonSlidingView="@id/non_sliding_view"
  app:slidingView="@id/sliding_view"
  app:slidingState="expanded"
  app:elevation="4dp" >

and i can't use slidinsgState

**Comment by iRYO400** [comment]
Okay, I got you...

**Comment by iRYO400** [comment]
Don't know why, jitpack version `implementation 'com.github.iRYO400:sliding-panel:1.3.1'` doesn't work right now, mby it need some time before being cached, but for now you can use directly .aar from release section

https://github.com/iRYO400/sliding-panel/releases

**Comment by marekbil** [comment]
I call in onCreate() in activity

slidingPanel.slideTo(PanelState.EXPANDED);

but it error:
java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.novitus.bill/pl.novitus.bill.ui.sale.SaleActivity}: kotlin.UninitializedPropertyAccessException: lateinit property slidingView has not been initialized
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)

**Comment by iRYO400** [comment]
you can define default state in the xml, instead of calling it before it's drawn

**Comment by iRYO400** [comment]
As stated before library is available via [jitpack.io](https://jitpack.io/#iRYO400/sliding-panel/1.4.0) 
```
implementation 'com.github.iRYO400:sliding-panel:1.4.0'
```

P.S. with updates - `targetSdk = 33`
